name: Automation Pipe

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run API tests
        working-directory: api-tests
        run: mvn clean test

      - name: Upload API report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-tests-report
          path: api-tests/target

  e2e-tests:
    name: E2E Tests (Cucumber + Selenium)
    needs: api-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run E2E tests
        working-directory: e2e-tests
        run: mvn clean test

      - name: Upload E2E report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-report
          path: e2e-tests/target
